version: "2"
networks:
  my-network:
services:
  monolito:
    build: ./Monolito
    networks:
      my-network:
        aliases:
          - monolitodocker
  nginx:
    image: nginx:1.13.7
    ports:
      - "80:80"
    depends_on:
      - monolito
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
