version: '3'
services:
 broker:
  build: ./Redirecciona
  networks:
      my-network:
        aliases:
          - broker
 usuarios:
  build: ./ControlUsuarios
  networks:
      my-network:
        aliases:
          - usuarios
 cuestionarios:
  build: ./ControlCuestionarios
  networks:
      my-network:
        aliases:
          - cuestionarios
 operaciones:
  build: ./AccionesCuestionarios
  networks:
      my-network:
        aliases:
          - operaciones
 nginx:
    image: nginx:1.13.7
    ports:
      - "5000:80"
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  my-network:
